# Generated by Django 4.1.1 on 2022-09-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estadio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Capacidad', models.IntegerField()),
                ('Disponible', models.BooleanField()),
                ('Partido_a_disputar', models.CharField(max_length=100)),
                ('Fecha', models.DateField()),
            ],
        ),
    ]
