# Generated by Django 4.1.1 on 2022-09-19 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=32)),
                ('Entrenador', models.CharField(max_length=32)),
                ('Total_de_jugadores', models.IntegerField()),
                ('Total_de_Partidos', models.IntegerField()),
                ('Total_de_puntos', models.IntegerField()),
                ('Clasificado', models.BooleanField(default=False)),
            ],
        ),
    ]
