# Generated by Django 4.1.1 on 2022-09-17 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=32)),
                ('Entrenador', models.CharField(max_length=32)),
                ('Total_de_jugadores', models.IntegerField()),
                ('Total_de_Partidos', models.IntegerField()),
                ('Total_de_puntos', models.IntegerField()),
                ('Clasificado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Estadio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Capacidad', models.IntegerField()),
                ('Disponible', models.BooleanField()),
                ('Partido_a_disputar', models.CharField(max_length=100)),
                ('Fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Jugadore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Edad', models.IntegerField()),
                ('Numero', models.IntegerField()),
                ('Equipo_perteneciente', models.CharField(max_length=50)),
                ('Fecha_de_ingreso_al_equipo', models.DateField()),
                ('Estatus', models.BooleanField(default=True)),
            ],
        ),
    ]
